### ISSUE TITLE
Ace Integration 

### ISSUE THREAD

**Issue by agjaeger** [agjaeger/CodeBin#1]
Currently, Skulpt pulls code from the editor div, however after trying to use Ace as a text editor, Skulpt was unable to load the new code into the interpreter

In order to fix problem, I feel it might be necessary to create a temporary div that JS can pull the code from the editor, place it in the temp div and then Skulpt can interpret it and output the result to the output div.

As a quick fix, a text area has replaced Ace, as it allows Skulpt to pull its contents as the run button is pressed. I recommend modeling Ace after the text area with the temporary div.

**Comment by cptaffe** [comment]
You can use this answer from [stackoverflow](http://stackoverflow.com/a/8976742)

``` js
var code = editor.getSession().getValue();
```

You can implement this, for example, by editing a line in the [example gist](https://gist.github.com/bnmnetp/4650616#file-simpleskulpt-html) in the function `runit()`:

``` js
// Original code
var prog = document.getElementById("yourcode").value;
// Using Ace Editor
var prog = editor.getSession().getValue();
```
