### ISSUE TITLE
Skulpt Error Messages

### ISSUE THREAD

**Issue by agjaeger** [agjaeger/CodeBin#2]
Since Skulpt is Python that is interpreted with JavaScript, error messages do not transfer to the end user and leaves the output div empty. 

In order to fix, either a different library or a Virtual Machine Spawner is required

**Comment by cptaffe** [comment]
It seems Skulpt stores errors in an `Sk.builtin.Exception` object, as explained in the comment atop this file: [errors.js](https://github.com/skulpt/skulpt/blob/master/src/errors.js)

> The filename, line number, and column number of exceptions are stored within the exception object. Note that not all exceptions clearly report the column number. To customize the exception message to use any/all of these fields, you can either modify tp$str below to print the desired message, or use them in the skulpt wrapper (i.e., runit) to present the exception message.

It seems it already prints errors to the console, and the **errors.js** file indicates this _might_ work in the [example gist](https://gist.github.com/bnmnetp/4650616#file-simpleskulpt-html) within `runit()`

``` js
document.getElementById("errorout").value = Sk.builtin.Exception.toString();
```
